version: '3.8'

services:
  backend:
    container_name: PG50537-CVTool-Back-End
    build:
      context: ./CVTool-Back-End
    ports:
      - "50761:50761"
    volumes:
      - ./CVTool-Back-End:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    container_name: PG50537-CVTool-Front-End
    build:
      context: ./CVTool-Front-End
    ports:
      - "50760:50760"
    volumes:
      - ./CVTool-Front-End:/app
    stdin_open: true
    tty: true
